dist: trusty
language: java
jdk:
  - oraclejdk8
before_script:
  - sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start +extension RANDR +render -noreset
  - sleep 5 # give xvfb some time to start
script:
  - "./gradlew clean check"
  - "./gradlew checkTest"
after_success:
  - ./gradlew coveralls